# Site settings
title: Lei's Blog
SEOTitle: Lei's Blog
header-img: img/post-bg-desk.jpg
email: lgao1024@outlook.com
description: "Every failure is leading towards success."
keyword: "Lei, Lei's Blog, LeiGao"
url: "https://lgao1024.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lgao1024/lgao1024.github.io.git" # you code repository

# Sidebar settings
sidebar: false                          # whether or not using Sidebar.
sidebar-about-description: "Website for chemistry and coding!"
sidebar-avatar: /img/about-lgao-profile.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     lgao1024
zhihu_username:     lgao1024
github_username:    lgao1024
#facebook_username:  lgao1024
#jianshu_username:   lgao1024
#twitter_username:   lgao1024




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 鐠囧嫯顔戠化鑽ょ埠
# Disqus閿涘潝ttps://disqus.com/閿?
# disqus_username: lgao1024

# Gitalk
# gitalk:
#   enable: true    #閺勵垰鎯佸鈧崥鐤搃talk鐠囧嫯顔?
#   clientID: f2c84e7629bb1446c1a4                            #閻㈢喐鍨氶惃鍒ientID
#   clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #閻㈢喐鍨氶惃鍒ientSecret
#   repo: lgao1024.github.io    # repository name
#   owner: lgao1024    # github username
#   admin: lgao1024
#   distractionFreeMode: true #閺勵垰鎯侀崥顖滄暏缁鎶€FB閻ㄥ嫰妲捐ぐ閬嶄紕缂?


# 缂佺喕顓?

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: lgao1024.github.io          # default: auto, optional custom domain





# Featured Tags
featured-tags: true                     # 閺勵垰鎯佹担璺ㄦ暏妫ｆ牠銆夐弽鍥╊劮
featured-condition-size: 0              # 閻╃鎮撻弽鍥╊劮閺佷即鍣烘径褌绨潻娆庨嚋閺佸府绱濋幍宥勭窗閸戣櫣骞囬崷銊╊浕妞?



# Friends
friends: [
    {
        title: "NJU",
        href: "https://www.nju.edu.cn/"
    },
    {
        title: "Yuangroup",
        href: "https://www.x-mol.com/groups/yuangroup/publications"
    }
]


