# 网站图标设置
favicon: /img/favicon.ico  # 网站图标，显示在浏览器标签页

# 导航菜单设置
menu:
  首页: /                   # 首页链接
  归档: /archives/          # 文章归档
  分类: /categories/        # 文章分类
  标签: /tags/              # 文章标签
  关于: /about/             # 关于页面

# 社交链接设置
social:
  GitHub: https://github.com/lgao1024  # GitHub链接
  # 微博: https://weibo.com/你的用户名     # 微博链接
  知乎: https://www.zhihu.com/people/lgao1024  # 知乎链接

busuanzi:
  site_uv: false
  site_pv: false
  page_pv: false